/**
 * PaymentAdvisoryPortalAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface BillsForReportDto { 
    billID?: number;
    isPending?: number;
    isProcessed?: number;
    invoiceNo?: string;
    bankName?: string;
    state?: string;
    lhoName?: string;
    serviceType?: string;
    invoiceYear?: number;
    invoiceMonth?: string;
    dateOfSubmission?: string;
    invoiceAmountPaid?: number;
    invoiceAmountPaidNavision?: number;
    cnDetails?: string;
    incentiveDNDetails?: string;
    fosDetails?: string;
    downtimeDetails?: string;
    cashOutPenaltyDetails?: string;
    houseKeepingDetails?: string;
    rejectBinDetails?: string;
    consumableDetails?: string;
    dosDetails?: string;
    excessBillingDetails?: string;
    incentiveAmountWithoutDNDetails?: string;
    reconPenaltyDetails?: string;
    ejDeductionDetails?: string;
    essFootagesDetails?: string;
    eSurDowntimeDetails?: string;
    eSurNotInstalledDetails?: string;
    craServicesDetails?: string;
    robberyDetails?: string;
    cashMisappropriationDetails?: string;
    adjustedAmount?: number;
}