/**
 * PaymentAdvisoryPortalAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface FiltersDto { 
    banks?: Array<string>;
    invoiceMonths?: Array<string>;
    invoiceYears?: Array<number>;
    states?: Array<string>;
    lhoNames?: Array<string>;
    serviceTypes?: Array<string>;
}