/**
 * PaymentAdvisoryPortalAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InvoiceDetailsDto { 
    invoiceNo?: string;
    isPending?: number;
    isProcessed?: number;
    lhoName?: string;
    bankName?: string;
    state?: string;
    serviceType?: string;
    dateOfSubmission?: string;
    invoiceYear?: number;
    invoiceMonth?: string;
    atmCount?: number;
    finUserRemark?: string;
    isAcknowledged?: number;
    ackDate?: string;
    ackProof?: string;
    lhoUserRemark?: string;
    isCreditNoteGiven?: boolean;
    creditNoteNo?: string;
    debitNoteNo?: string;
    deductionRemarks?: string;
    invoiceAmount?: number;
    invoiceAmountWithGST?: number;
    invoiceAmountPaid?: number;
    invoiceAmountPaidNavision?: number;
    invoiceAmountPaidDate?: string;
    cnDetails?: string;
    incentiveDNDetails?: string;
    withoutDNDetails?: string;
    withoutCNDetails?: string;
    tdsDetails?: string;
    gsttdsDetails?: string;
    remainingDetails?: string;
    fosDetails?: string;
    fosAttachment?: string;
    downtimeDetails?: string;
    downtimeAttachment?: string;
    cashOutPenaltyDetails?: string;
    cashOutPenaltyAttachment?: string;
    houseKeepingDetails?: string;
    houseKeepingAttachment?: string;
    rejectBinDetails?: string;
    rejectBinAttachment?: string;
    consumableDetails?: string;
    consumableAttachment?: string;
    dosDetails?: string;
    dosAttachment?: string;
    excessBillingDetails?: string;
    excessBillingAttachment?: string;
    slaPenaltyDetails?: string;
    slaPenaltyAttachment?: string;
    reconPenaltyDetails?: string;
    reconPenaltyAttachment?: string;
    ejDeductionDetails?: string;
    ejDeductionAttachment?: string;
    essFootagesDetails?: string;
    essFootagesAttachment?: string;
    eSurDowntimeDetails?: string;
    eSurDowntimeAttachment?: string;
    eSurNotInstalledDetails?: string;
    eSurNotInstalledAttachment?: string;
    craServicesDetails?: string;
    craServicesAttachment?: string;
    robberyDetails?: string;
    robberyAttachment?: string;
    cashMisappropriationDetails?: string;
    cashMisappropriationAttachment?: string;
    adjustedAmount?: number;
}