/**
 * PaymentAdvisoryPortalAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { BillsForDashboardDto } from '../model/billsForDashboardDto';
import { InvoiceDetailsDto } from '../model/invoiceDetailsDto';
import { InvoiceDetailsToUpdateDto } from '../model/invoiceDetailsToUpdateDto';
import { InvoiceToGetDto } from '../model/invoiceToGetDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class BillService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public billGetInvoiceDetailsGet(body?: InvoiceToGetDto, observe?: 'body', reportProgress?: boolean): Observable<InvoiceDetailsDto>;
    public billGetInvoiceDetailsGet(body?: InvoiceToGetDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InvoiceDetailsDto>>;
    public billGetInvoiceDetailsGet(body?: InvoiceToGetDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InvoiceDetailsDto>>;
    public billGetInvoiceDetailsGet(body?: InvoiceToGetDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<InvoiceDetailsDto>('get',`${this.basePath}/Bill/GetInvoiceDetails`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public billGetPendingBillsGet(observe?: 'body', reportProgress?: boolean): Observable<Array<BillsForDashboardDto>>;
    public billGetPendingBillsGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<BillsForDashboardDto>>>;
    public billGetPendingBillsGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<BillsForDashboardDto>>>;
    public billGetPendingBillsGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<BillsForDashboardDto>>('get',`${this.basePath}/Bill/GetPendingBills`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public billGetProcessedBillsGet(observe?: 'body', reportProgress?: boolean): Observable<Array<BillsForDashboardDto>>;
    public billGetProcessedBillsGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<BillsForDashboardDto>>>;
    public billGetProcessedBillsGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<BillsForDashboardDto>>>;
    public billGetProcessedBillsGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<BillsForDashboardDto>>('get',`${this.basePath}/Bill/GetProcessedBills`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public billGetTotalBillsGet(observe?: 'body', reportProgress?: boolean): Observable<Array<BillsForDashboardDto>>;
    public billGetTotalBillsGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<BillsForDashboardDto>>>;
    public billGetTotalBillsGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<BillsForDashboardDto>>>;
    public billGetTotalBillsGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<BillsForDashboardDto>>('get',`${this.basePath}/Bill/GetTotalBills`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public billUpdateInvoiceDetailsPost(body?: InvoiceDetailsToUpdateDto, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public billUpdateInvoiceDetailsPost(body?: InvoiceDetailsToUpdateDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public billUpdateInvoiceDetailsPost(body?: InvoiceDetailsToUpdateDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public billUpdateInvoiceDetailsPost(body?: InvoiceDetailsToUpdateDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/Bill/UpdateInvoiceDetails`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
