/**
 * PaymentAdvisoryPortalAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { BillsForDashboardDto } from '../model/billsForDashboardDto';
import { BillsForReportDto } from '../model/billsForReportDto';
import { InvoiceDateOfSubmissionDto } from '../model/invoiceDateOfSubmissionDto';
import { InvoiceDetailsDto } from '../model/invoiceDetailsDto';
import { InvoiceDetailsToUpdateDto } from '../model/invoiceDetailsToUpdateDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class InvoiceService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public invoiceGetAllBillsGet(observe?: 'body', reportProgress?: boolean): Observable<Array<BillsForDashboardDto>>;
    public invoiceGetAllBillsGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<BillsForDashboardDto>>>;
    public invoiceGetAllBillsGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<BillsForDashboardDto>>>;
    public invoiceGetAllBillsGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<BillsForDashboardDto>>('get',`${this.basePath}/Invoice/GetAllBills`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param billId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public invoiceGetInvoiceDetailsBillIdGet(billId: number, observe?: 'body', reportProgress?: boolean): Observable<InvoiceDetailsDto>;
    public invoiceGetInvoiceDetailsBillIdGet(billId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InvoiceDetailsDto>>;
    public invoiceGetInvoiceDetailsBillIdGet(billId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InvoiceDetailsDto>>;
    public invoiceGetInvoiceDetailsBillIdGet(billId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (billId === null || billId === undefined) {
            throw new Error('Required parameter billId was null or undefined when calling invoiceGetInvoiceDetailsBillIdGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<InvoiceDetailsDto>('get',`${this.basePath}/Invoice/GetInvoiceDetails/${encodeURIComponent(String(billId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public invoiceGetPendingBillsGet(observe?: 'body', reportProgress?: boolean): Observable<Array<BillsForDashboardDto>>;
    public invoiceGetPendingBillsGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<BillsForDashboardDto>>>;
    public invoiceGetPendingBillsGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<BillsForDashboardDto>>>;
    public invoiceGetPendingBillsGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<BillsForDashboardDto>>('get',`${this.basePath}/Invoice/GetPendingBills`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public invoiceGetProcessedBillsGet(observe?: 'body', reportProgress?: boolean): Observable<Array<BillsForDashboardDto>>;
    public invoiceGetProcessedBillsGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<BillsForDashboardDto>>>;
    public invoiceGetProcessedBillsGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<BillsForDashboardDto>>>;
    public invoiceGetProcessedBillsGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<BillsForDashboardDto>>('get',`${this.basePath}/Invoice/GetProcessedBills`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public invoiceGetReportsGet(observe?: 'body', reportProgress?: boolean): Observable<Array<BillsForReportDto>>;
    public invoiceGetReportsGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<BillsForReportDto>>>;
    public invoiceGetReportsGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<BillsForReportDto>>>;
    public invoiceGetReportsGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<BillsForReportDto>>('get',`${this.basePath}/Invoice/GetReports`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public invoiceUpdateDateOfSubmissionPost(body?: InvoiceDateOfSubmissionDto, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public invoiceUpdateDateOfSubmissionPost(body?: InvoiceDateOfSubmissionDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public invoiceUpdateDateOfSubmissionPost(body?: InvoiceDateOfSubmissionDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public invoiceUpdateDateOfSubmissionPost(body?: InvoiceDateOfSubmissionDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/Invoice/UpdateDateOfSubmission`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public invoiceUpdateInvoiceDetailsPost(body?: InvoiceDetailsToUpdateDto, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public invoiceUpdateInvoiceDetailsPost(body?: InvoiceDetailsToUpdateDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public invoiceUpdateInvoiceDetailsPost(body?: InvoiceDetailsToUpdateDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public invoiceUpdateInvoiceDetailsPost(body?: InvoiceDetailsToUpdateDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/Invoice/UpdateInvoiceDetails`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
